### ISSUE TITLE
MUMIE problem  is opened in the same window despite setting "Launch container" = "new window"

### ISSUE THREAD

**Issue by inceylan** [integral-learning/moodle-mod_mumie#48]
The activity MUMIE task is behaving differently than it previously did. The setting "Launch container" = "new window" does not work. The MUMIE problem is opened in the same window (not embedded, in place of the Moodle window). This will lead to problems when students are asked to complete a series of "MUMIE Task" acitivties.
The problem only seems to occur since upgrading from Moodle 3.11.10 to 3.11.11. We are using the most recent MUMIE Task plugin, v1.4.8.

**Comment by jtgoltz** [comment]
Thank you for pointing that out. This error happend due to an caching issue on newer moodle versions. We've just relasead v1.4.9 that should fix this unexpected behavior.

**Comment by inceylan** [comment]
Yes, indeed. With mod_mumie v1.4.9 (2023011100) there is no issue in our Moodle system which runs 3.11.12+. Thank you.
