### ISSUE TITLE
Deprecated strpos warning on activity page

### ISSUE THREAD

**Issue by voegii** [integral-learning/moodle-mod_mumie#66]
1. As a teacher add a new Mumie activity.
2. Open the added activity page.
3. Ensure, that you have no table sorting.
4. You can see following warnings:

`Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /path/to/moodle/mod/mumie/classes/mumie_participants.php on line 287`

Moodle 4.2 with PHP 8.1 (Test server with enabled error reporting and debug display)

**Comment by Lyannic** [comment]
Thank you for reporting this. I just created a PR that solves this.
