### ISSUE TITLE
Callback before_standard_top_of_body_html is deprecated

### ISSUE THREAD

**Issue by voegii** [integral-learning/moodle-mod_mumie#83]
Since Moodle 4.4, the use of callback before_standard_top_of_body_html in lib.php is deprecated and should be migrated to the new hook system.

When debugging is enabled, following error exception occurs on every page: 
`Callback before_standard_top_of_body_html in mod_mumie component should be migrated to new hook callback for core\hook\output\before_standard_top_of_body_html_generation`.

See: 
- https://git.moodle.org/gw?p=moodle.git;a=blob;f=lib/upgrade.txt#l48
- https://moodledev.io/docs/4.4/apis/core/hooks#deprecation-of-legacy-libphp-callbacks

**Comment by Lyannic** [comment]
Thank you for pointing out the deprecation warning. While this does not affect our plugin's current functionality, it's helpful to know for future updates. We will plan to transition from the legacy lib.php callback to the new PSR-14 hook system to ensure compatibility with future Moodle versions.

**Comment by Lyannic** [comment]
I am closing this for now, because we are planning on addressing this when migrating to Moodle 4.5, for which we have an internal ticket.
